---
abstract: 'Use L<Dist::Zilla> like MSCHOUT does'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Module::Signature: 0
  Socket: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-MSCHOUT
requires:
  Dist::Zilla: 4.102341
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::BumpVersionFromGit: 0
  Dist::Zilla::Plugin::FakeRelease: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::Signature: 0
  Dist::Zilla::Plugin::TaskWeaver: 0.093330
  Dist::Zilla::PluginBundle::Classic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 1.101230
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Section::BugsRT: 0
  Pod::Weaver::Section::SourceGitHub: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-MSCHOUT
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-MSCHOUT/
  repository: git://github.com/mschout/dist-zilla-pluginbundle-mschout.git
version: 0.22
