---
abstract: 'Use L<Dist::Zilla> like MSCHOUT does'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Test::More: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-MSCHOUT
provides:
  Dist::Zilla::PluginBundle::MSCHOUT:
    file: lib/Dist/Zilla/PluginBundle/MSCHOUT.pm
    version: '0.38'
  Pod::Weaver::PluginBundle::MSCHOUT:
    file: lib/Pod/Weaver/PluginBundle/MSCHOUT.pm
    version: '0.38'
requires:
  Dist::Zilla: '4.102341'
  Dist::Zilla::Plugin::AuthorSignatureTest: '0'
  Dist::Zilla::Plugin::AutoPrereqs: '0'
  Dist::Zilla::Plugin::AutoVersion: '0'
  Dist::Zilla::Plugin::CheckPrereqsIndexed: '0'
  Dist::Zilla::Plugin::FakeRelease: '0'
  Dist::Zilla::Plugin::Git::NextVersion: '0'
  Dist::Zilla::Plugin::GithubMeta: '0'
  Dist::Zilla::Plugin::InsertCopyright: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaProvides::Package: '0'
  Dist::Zilla::Plugin::MinimumPerl: '0'
  Dist::Zilla::Plugin::NextRelease: '0'
  Dist::Zilla::Plugin::PodWeaver: '0'
  Dist::Zilla::Plugin::Prereqs::AuthorDeps: '0'
  Dist::Zilla::Plugin::RemovePrereqs: '0'
  Dist::Zilla::Plugin::Signature: '0'
  Dist::Zilla::Plugin::TaskWeaver: '0.093330'
  Dist::Zilla::Plugin::TravisYML: '0'
  Dist::Zilla::Plugin::Twitter: '0'
  Dist::Zilla::PluginBundle::Classic: '0'
  Dist::Zilla::PluginBundle::Filter: '0'
  Dist::Zilla::PluginBundle::Git: '1.101230'
  Dist::Zilla::Role::PluginBundle::Config::Slicer: '0'
  Dist::Zilla::Role::PluginBundle::Easy: '0'
  Dist::Zilla::Role::PluginBundle::PluginRemover: '0'
  Moose: '0'
  MooseX::AttributeShortcuts: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Config::Assembler: '0'
  Pod::Weaver::Plugin::SingleEncoding: '0'
  Pod::Weaver::Section::AllowOverride: '0'
  Pod::Weaver::Section::Bugs: '0'
  Pod::Weaver::Section::SourceGitHub: '0'
  namespace::autoclean: '0.09'
  perl: '5.006'
resources:
  bugtracker: https://github.com/mschout/dist-zilla-pluginbundle-mschout/issues
  homepage: https://github.com/mschout/dist-zilla-pluginbundle-mschout
  repository: https://github.com/mschout/dist-zilla-pluginbundle-mschout.git
version: '0.38'
x_serialization_backend: 'YAML::Tiny version 1.70'
